# version: "3.9"

# services:
#   fandom_app:
#     build:
#       dockerfile: Dockerfile
#     # volumes:
#     #   - .:/rails:cached
#     #   - .:/rails:rw
#     environment:
#       - RAILS_MASTER_KEY=4ed2c966852a224490b3140f224f957b
#     ports:
#       - '3000:3000'

# version: "3.8"

services:
  fandom_app:
    build:
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      RAILS_ENV: test
      DATABASE_HOST: db
      DATABASE_USERNAME: user
      DATABASE_PASSWORD: password
      DATABASE_DB: fandomApp
      RAILS_MASTER_KEY: 4ed2c966852a224490b3140f224f957b
    ports:
      - '3000:3000'

  db:
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: fandomApp
    volumes:
      - postgres_data:/var/lib/postgresql/data # Persist PostgreSQL data

volumes:
  postgres_data: # Define a named volume for PostgreSQL data persistence